import os
import datetime
import random

SPRITE_DIR = "Sprites/user's"

def _today_date():
    return datetime.date.today().isoformat()

class User_SpritesManager:
    def __init__(self):
        self.sprites_by_outfit = self._load_sprites()
        self.valid = self._extract_all_emotions()
        self._selected_casual_variant = None
        self._last_casual_date  = None

    def _load_sprites(self):
        return {
            "school_uniform": {
                "happy": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon1.png",
                "smile speaking": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon2.png",
                "lean smile": f"{SPRITE_DIR}/school_uniform/Full_sprite/3aa.png",
                "lean smile eyes close": f"{SPRITE_DIR}/school_uniform/Full_sprite/3ab.png",
                "lean happy eyes close speaking": f"{SPRITE_DIR}/school_uniform/Full_sprite/3ac.png",
                "lean happy speaking": f"{SPRITE_DIR}/school_uniform/Full_sprite/3ad.png",
                "lean happy wink": f"{SPRITE_DIR}/school_uniform/Full_sprite/3ae.png",
                "eyes close smile": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon10.png",
                "eyes close smile speaking": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon11.png",
                "pointing finger smile": f"{SPRITE_DIR}/school_uniform/Full_sprite/Ika9.png",
                "lean wink point smile": f"{SPRITE_DIR}/school_uniform/Full_sprite/3Ika.png",
                "sad": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon6.png",
                "crying": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon20.png",
                "sad smile": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon5.png",
                "neutral": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon3.png",
                "eyes close neutral": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon17.png",
                "neutral speaking": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon4.png",
                "eyes close neutral speaking": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon18.png",
                "pissed lean": f"{SPRITE_DIR}/school_uniform/Full_sprite/3bd.png",
                "mad speaking lean": f"{SPRITE_DIR}/school_uniform/Full_sprite/3ba.png",
                "mad leaning": f"{SPRITE_DIR}/school_uniform/Full_sprite/3bb.png",
                "mad pitting face lean": f"{SPRITE_DIR}/school_uniform/Full_sprite/3bc.png",
                "horrified screams": f"{SPRITE_DIR}/school_uniform/Full_sprite/HorrifiedMonika8.png",
                "horrified speaking": f"{SPRITE_DIR}/school_uniform/Full_sprite/HorrifiedMonika5.png",
                "horrified babbling": f"{SPRITE_DIR}/school_uniform/Full_sprite/HorrifiedMonika6.png",
                "horrified surprised": f"{SPRITE_DIR}/school_uniform/Full_sprite/HorrifiedMonika4.png",
                "horrified no words": f"{SPRITE_DIR}/school_uniform/Full_sprite/HorrifiedMonika3.png",
                "horrified really surprised": f"{SPRITE_DIR}/school_uniform/Full_sprite/HorrifiedMonika2.png",
                "horrified": f"{SPRITE_DIR}/school_uniform/Full_sprite/HorrifiedMonika1.png",
                "horrified concerned": f"{SPRITE_DIR}/school_uniform/Full_sprite/HorrifiedMonika7.png",
                "serious": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon8.png",
                "ever serious": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon21.png",
                "disappointed": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon21.png",
                "serious pointing speaking": f"{SPRITE_DIR}/school_uniform/Full_sprite/Ika8.png",
                "serious pointing": f"{SPRITE_DIR}/school_uniform/Full_sprite/Ika7.png",
                "serious speaking": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon9.png",
                "serious pointing eyes close": f"{SPRITE_DIR}/school_uniform/Full_sprite/Ika15.png",
                "serious pointing speaking eyes close": f"{SPRITE_DIR}/school_uniform/Full_sprite/Ika16.png",
                "concerned": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon6.png",
                "concerned pointing": f"{SPRITE_DIR}/school_uniform/Full_sprite/Ika13.png",
                "concerned pointing speaking": f"{SPRITE_DIR}/school_uniform/Full_sprite/Ika14.png",
                "sad pointing smile looks away": f"{SPRITE_DIR}/school_uniform/Full_sprite/Ika12.png",
                "sad pointing smile": f"{SPRITE_DIR}//school_uniform/Full_sprite/Ika5.png",
                "sad pointing": f"{SPRITE_DIR}/school_uniform/Full_sprite/Ika6.png",
                "sad pointing smile speaking": f"{SPRITE_DIR}/school_uniform/Full_sprite/Ika11.png",
                "smile pointing speaking": f"{SPRITE_DIR}/school_uniform/Full_sprite/Ika10.png",
                "happy pointing speaking": f"{SPRITE_DIR}/school_uniform/Full_sprite/Ika2.png",
                "happy pointing": f"{SPRITE_DIR}/school_uniform/Full_sprite/Ika1.png",
                "neutral pointing speaking": f"{SPRITE_DIR}/school_uniform/Full_sprite/Ika4.png",
                "neutral pointing": f"{SPRITE_DIR}/school_uniform/Full_sprite/Ika3.png",
                "concerned speaking": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon7.png",
                "embarrass": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon19.png",
                "blushing with her eyes close": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon19.png",
                "smirk lean": f"{SPRITE_DIR}/school_uniform/Full_sprite/3ca.png",
                "leaning kiss": f"{SPRITE_DIR}/school_uniform/Full_sprite/3cb.png",
                "blushing leaning": f"{SPRITE_DIR}/school_uniform/Full_sprite/3cc.png",
                "surprise speaking lean": f"{SPRITE_DIR}/school_uniform/Full_sprite/3da.png",
                "concerned speaking lean": f"{SPRITE_DIR}/school_uniform/Full_sprite/3ea.png",
                "my brother in christ": f"{SPRITE_DIR}/school_uniform/Full_sprite/3fa.png",
                "your joking. right?": f"{SPRITE_DIR}/school_uniform/Full_sprite/3fa.png",
                "nervous": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon13.png",
                "really nervous": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon15.png",
                "has a gun": f"{SPRITE_DIR}/school_uniform/Full_sprite/Gun.png",
                "oh shit she packing heat!": f"{SPRITE_DIR}/school_uniform/Full_sprite/Gun.png",
                "threatened": f"{SPRITE_DIR}/school_uniform/Full_sprite/with_gun.png",
                "nervous speaking": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon16.png",
                "nervous laughing": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon14.png",
                "nervous laughing eyes close": f"{SPRITE_DIR}/school_uniform/Full_sprite/Mon12.png",
                "thinking": f"{SPRITE_DIR}/school_uniform/Full_sprite/T1.png",
                "don't sure": f"{SPRITE_DIR}/school_uniform/Full_sprite/IDK.png",
                "Infinity Gauntlet": f"{SPRITE_DIR}/school_uniform/Full_sprite/Monika_Infinity_Gauntlet_Sprite_Animation.webp"
            },
            "error": {
                "error": f"{SPRITE_DIR}/school_uniform/Full_sprite/G1.png",
                "glitching": f"{SPRITE_DIR}/school_uniform/Full_sprite/G5.gif"
            },
            "casual_variants": {
                "casual 1": {
                    "happy": f"{SPRITE_DIR}/casual/1/Mon1.png",
                    "smile speaking": f"{SPRITE_DIR}/casual/1/Mon2.png",
                    "lean smile": f"{SPRITE_DIR}/casual/1/3aa.png",
                    "lean smile eyes close": f"{SPRITE_DIR}/casual/1/3ab.png",
                    "lean happy eyes close speaking": f"{SPRITE_DIR}/casual/1/3ac.png",
                    "lean happy speaking": f"{SPRITE_DIR}/casual/1/3ad.png",
                    "lean happy wink": f"{SPRITE_DIR}/casual/1/3ae.png",
                    "eyes close smile": f"{SPRITE_DIR}/casual/1/Mon10.png",
                    "eyes close smile speaking": f"{SPRITE_DIR}/casual/1/Mon11.png",
                    "pointing finger smile": f"{SPRITE_DIR}/casual/1/Ika9.png",
                    "sad": f"{SPRITE_DIR}/casual/1/Mon6.png",
                    "crying": f"{SPRITE_DIR}/casual/1/Mon20.png",
                    "sad smile": f"{SPRITE_DIR}/casual/1/Mon5.png",
                    "neutral": f"{SPRITE_DIR}/casual/1/Mon3.png",
                    "eyes close neutral": f"{SPRITE_DIR}/casual/1/Mon17.png",
                    "neutral speaking": f"{SPRITE_DIR}/casual/1/Mon4.png",
                    "eyes close neutral speaking": f"{SPRITE_DIR}/casual/1/Mon18.png",
                    "pissed lean": f"{SPRITE_DIR}/casual/1/3bd.png",
                    "mad speaking lean": f"{SPRITE_DIR}/casual/1/3ba.png",
                    "mad leaning": f"{SPRITE_DIR}/casual/1/3bb.png",
                    "mad pitting face lean": f"{SPRITE_DIR}/casual/1/3bc.png",
                    "horrified screams": f"{SPRITE_DIR}/casual/1/HorrifiedMonika8.png",
                    "horrified speaking": f"{SPRITE_DIR}/casual/1/HorrifiedMonika5.png",
                    "horrified babbling": f"{SPRITE_DIR}/casual/1/HorrifiedMonika6.png",
                    "horrified surprised": f"{SPRITE_DIR}/casual/1/HorrifiedMonika4.png",
                    "horrified no words": f"{SPRITE_DIR}/casual/1/HorrifiedMonika3.png",
                    "horrified really surprised": f"{SPRITE_DIR}/casual/1/HorrifiedMonika2.png",
                    "horrified": f"{SPRITE_DIR}/casual/1/HorrifiedMonika1.png",
                    "horrified concerned": f"{SPRITE_DIR}/casual/1/HorrifiedMonika7.png",
                    "serious": f"{SPRITE_DIR}/casual/1/Mon8.png",
                    "ever serious": f"{SPRITE_DIR}/casual/1/Mon21.png",
                    "disappointed": f"{SPRITE_DIR}/casual/1/Mon21.png",
                    "serious pointing speaking": f"{SPRITE_DIR}/casual/1/Ika8.png",
                    "serious pointing": f"{SPRITE_DIR}/casual/1/Ika7.png",
                    "serious speaking": f"{SPRITE_DIR}/casual/1/Mon9.png",
                    "serious pointing eyes close": f"{SPRITE_DIR}/casual/1/Ika15.png",
                    "serious pointing speaking eyes close": f"{SPRITE_DIR}/casual/1/Ika16.png",
                    "concerned": f"{SPRITE_DIR}/casual/1/Mon6.png",
                    "concerned pointing": f"{SPRITE_DIR}/casual/1/Ika13.png",
                    "concerned pointing speaking": f"{SPRITE_DIR}/casual/1/Ika14.png",
                    "sad pointing smile looks away": f"{SPRITE_DIR}/casual/1/Ika12.png",
                    "sad pointing smile": f"{SPRITE_DIR}//casual/1/Ika5.png",
                    "sad pointing": f"{SPRITE_DIR}/casual/1/Ika6.png",
                    "sad pointing smile speaking": f"{SPRITE_DIR}/casual/1/Ika11.png",
                    "smile pointing speaking": f"{SPRITE_DIR}/casual/1/Ika10.png",
                    "happy pointing speaking": f"{SPRITE_DIR}/casual/1/Ika2.png",
                    "happy pointing": f"{SPRITE_DIR}/casual/1/Ika1.png",
                    "neutral pointing speaking": f"{SPRITE_DIR}/casual/1/Ika4.png",
                    "neutral pointing": f"{SPRITE_DIR}/casual/1/Ika3.png",
                    "concerned speaking": f"{SPRITE_DIR}/casual/1/Mon7.png",
                    "embarrass": f"{SPRITE_DIR}/casual/1/Mon19.png",
                    "blushing with her eyes close": f"{SPRITE_DIR}/casual/1/Mon19.png",
                    "leaning kiss": f"{SPRITE_DIR}/casual/1/3cb.png",
                    "blushing leaning": f"{SPRITE_DIR}/casual/1/3cc.png",
                    "surprise speaking lean": f"{SPRITE_DIR}/casual/1/3da.png",
                    "concerned speaking lean": f"{SPRITE_DIR}/casual/1/3ea.png",
                    "my brother in christ": f"{SPRITE_DIR}/casual/1/3fa.png",
                    "your joking. right?": f"{SPRITE_DIR}/casual/1/3fa.png",
                    "nervous": f"{SPRITE_DIR}/casual/1/Mon13.png",
                    "really nervous": f"{SPRITE_DIR}/casual/1/Mon15.png",
                    "nervous speaking": f"{SPRITE_DIR}/casual/1/Mon16.png",
                    "nervous laughing": f"{SPRITE_DIR}/casual/1/Mon14.png",
                    "nervous laughing eyes close": f"{SPRITE_DIR}/casual/1/Mon12.png",
                },
                "casual 2": {
                    "happy": f"{SPRITE_DIR}/casual/2/Mon1.png",
                    "smile speaking": f"{SPRITE_DIR}/casual/2/Mon2.png",
                    "eyes close smile": f"{SPRITE_DIR}/casual/2/Mon10.png",
                    "eyes close smile speaking": f"{SPRITE_DIR}/casual/2/Mon11.png",
                    "pointing finger smile": f"{SPRITE_DIR}/casual/2/Ika9.png",
                    "sad": f"{SPRITE_DIR}/casual/2/Mon6.png",
                    "crying": f"{SPRITE_DIR}/casual/2/Mon20.png",
                    "sad smile": f"{SPRITE_DIR}/casual/2/Mon5.png",
                    "neutral": f"{SPRITE_DIR}/casual/2/Mon3.png",
                    "eyes close neutral": f"{SPRITE_DIR}/casual/2/Mon17.png",
                    "neutral speaking": f"{SPRITE_DIR}/casual/2/Mon4.png",
                    "eyes close neutral speaking": f"{SPRITE_DIR}/casual/2/Mon18.png",
                    "horrified screams": f"{SPRITE_DIR}/casual/2/HorrifiedMonika8.png",
                    "horrified speaking": f"{SPRITE_DIR}/casual/2/HorrifiedMonika5.png",
                    "horrified babbling": f"{SPRITE_DIR}/casual/2/HorrifiedMonika6.png",
                    "horrified surprised": f"{SPRITE_DIR}/casual/2/HorrifiedMonika4.png",
                    "horrified no words": f"{SPRITE_DIR}/casual/2/HorrifiedMonika3.png",
                    "horrified really surprised": f"{SPRITE_DIR}/casual/2/HorrifiedMonika2.png",
                    "horrified": f"{SPRITE_DIR}/casual/2/HorrifiedMonika1.png",
                    "horrified concerned": f"{SPRITE_DIR}/casual/2/HorrifiedMonika7.png",
                    "serious": f"{SPRITE_DIR}/casual/2/Mon8.png",
                    "ever serious": f"{SPRITE_DIR}/casual/2/Mon21.png",
                    "disappointed": f"{SPRITE_DIR}/casual/2/Mon21.png",
                    "serious pointing speaking": f"{SPRITE_DIR}/casual/2/Ika8.png",
                    "serious pointing": f"{SPRITE_DIR}/casual/2/Ika7.png",
                    "serious speaking": f"{SPRITE_DIR}/casual/2/Mon9.png",
                    "serious pointing eyes close": f"{SPRITE_DIR}/casual/2/Ika15.png",
                    "serious pointing speaking eyes close": f"{SPRITE_DIR}/casual/2/Ika16.png",
                    "concerned": f"{SPRITE_DIR}/casual/2/Mon6.png",
                    "concerned pointing": f"{SPRITE_DIR}/casual/2/Ika13.png",
                    "concerned pointing speaking": f"{SPRITE_DIR}/casual/2/Ika14.png",
                    "sad pointing smile looks away": f"{SPRITE_DIR}/casual/2/Ika12.png",
                    "sad pointing smile": f"{SPRITE_DIR}//casual/2/Ika5.png",
                    "sad pointing": f"{SPRITE_DIR}/casual/2/Ika6.png",
                    "sad pointing smile speaking": f"{SPRITE_DIR}/casual/2/Ika11.png",
                    "smile pointing speaking": f"{SPRITE_DIR}/casual/2/Ika10.png",
                    "happy pointing speaking": f"{SPRITE_DIR}/casual/2/Ika2.png",
                    "happy pointing": f"{SPRITE_DIR}/casual/2/Ika1.png",
                    "neutral pointing speaking": f"{SPRITE_DIR}/casual/2/Ika4.png",
                    "neutral pointing": f"{SPRITE_DIR}/casual/2/Ika3.png",
                    "concerned speaking": f"{SPRITE_DIR}/casual/2/Mon7.png",
                    "embarrass": f"{SPRITE_DIR}/casual/2/Mon19.png",
                    "blushing with her eyes close": f"{SPRITE_DIR}/casual/2/Mon19.png",
                    "nervous": f"{SPRITE_DIR}/casual/2/Mon13.png",
                    "really nervous": f"{SPRITE_DIR}/casual/2/Mon15.png",
                    "nervous speaking": f"{SPRITE_DIR}/casual/2/Mon16.png",
                    "nervous laughing": f"{SPRITE_DIR}/casual/2/Mon14.png",
                    "nervous laughing eyes close": f"{SPRITE_DIR}/casual/2/Mon12.png",
                },
                "casual 3": {
                    "happy": f"{SPRITE_DIR}/casual/3/Mon1.png",
                    "smile speaking": f"{SPRITE_DIR}/casual/3/Mon2.png",
                    "eyes close smile": f"{SPRITE_DIR}/casual/3/Mon10.png",
                    "eyes close smile speaking": f"{SPRITE_DIR}/casual/3/Mon11.png",
                    "pointing finger smile": f"{SPRITE_DIR}/casual/3/Ika9.png",
                    "sad": f"{SPRITE_DIR}/casual/3/Mon6.png",
                    "crying": f"{SPRITE_DIR}/casual/3/Mon20.png",
                    "sad smile": f"{SPRITE_DIR}/casual/3/Mon5.png",
                    "neutral": f"{SPRITE_DIR}/casual/3/Mon3.png",
                    "eyes close neutral": f"{SPRITE_DIR}/casual/3/Mon17.png",
                    "neutral speaking": f"{SPRITE_DIR}/casual/3/Mon4.png",
                    "eyes close neutral speaking": f"{SPRITE_DIR}/casual/3/Mon18.png",
                    "horrified screams": f"{SPRITE_DIR}/casual/3/HorrifiedMonika8.png",
                    "horrified speaking": f"{SPRITE_DIR}/casual/3/HorrifiedMonika5.png",
                    "horrified babbling": f"{SPRITE_DIR}/casual/3/HorrifiedMonika6.png",
                    "horrified surprised": f"{SPRITE_DIR}/casual/3/HorrifiedMonika4.png",
                    "horrified no words": f"{SPRITE_DIR}/casual/3/HorrifiedMonika3.png",
                    "horrified really surprised": f"{SPRITE_DIR}/casual/3/HorrifiedMonika2.png",
                    "horrified": f"{SPRITE_DIR}/casual/3/HorrifiedMonika1.png",
                    "horrified concerned": f"{SPRITE_DIR}/casual/3/HorrifiedMonika7.png",
                    "serious": f"{SPRITE_DIR}/casual/3/Mon8.png",
                    "ever serious": f"{SPRITE_DIR}/casual/3/Mon21.png",
                    "disappointed": f"{SPRITE_DIR}/casual/3/Mon21.png",
                    "serious pointing speaking": f"{SPRITE_DIR}/casual/3/Ika8.png",
                    "serious pointing": f"{SPRITE_DIR}/casual/3/Ika7.png",
                    "serious speaking": f"{SPRITE_DIR}/casual/3/Mon9.png",
                    "serious pointing eyes close": f"{SPRITE_DIR}/casual/3/Ika15.png",
                    "serious pointing speaking eyes close": f"{SPRITE_DIR}/casual/3/Ika16.png",
                    "concerned": f"{SPRITE_DIR}/casual/3/Mon6.png",
                    "concerned pointing": f"{SPRITE_DIR}/casual/3/Ika13.png",
                    "concerned pointing speaking": f"{SPRITE_DIR}/casual/3/Ika14.png",
                    "sad pointing smile looks away": f"{SPRITE_DIR}/casual/3/Ika12.png",
                    "sad pointing smile": f"{SPRITE_DIR}//casual/3/Ika5.png",
                    "sad pointing": f"{SPRITE_DIR}/casual/3/Ika6.png",
                    "sad pointing smile speaking": f"{SPRITE_DIR}/casual/3/Ika11.png",
                    "smile pointing speaking": f"{SPRITE_DIR}/casual/3/Ika10.png",
                    "happy pointing speaking": f"{SPRITE_DIR}/casual/3/Ika2.png",
                    "happy pointing": f"{SPRITE_DIR}/casual/3/Ika1.png",
                    "neutral pointing speaking": f"{SPRITE_DIR}/casual/3/Ika4.png",
                    "neutral pointing": f"{SPRITE_DIR}/casual/3/Ika3.png",
                    "concerned speaking": f"{SPRITE_DIR}/casual/3/Mon7.png",
                    "embarrass": f"{SPRITE_DIR}/casual/3/Mon19.png",
                    "blushing with her eyes close": f"{SPRITE_DIR}/casual/3/Mon19.png",
                    "nervous": f"{SPRITE_DIR}/casual/3/Mon13.png",
                    "really nervous": f"{SPRITE_DIR}/casual/3/Mon15.png",
                    "nervous speaking": f"{SPRITE_DIR}/casual/3/Mon16.png",
                    "nervous laughing": f"{SPRITE_DIR}/casual/3/Mon14.png",
                    "nervous laughing eyes close": f"{SPRITE_DIR}/casual/3/Mon12.png",
                }
            },
            "hoodie": {
                "happy": f"{SPRITE_DIR}/hoodie/Mon1.png",
                "smile speaking": f"{SPRITE_DIR}/hoodie/Mon2.png",
                "eyes close smile": f"{SPRITE_DIR}/hoodie/Mon10.png",
                "eyes close smile speaking": f"{SPRITE_DIR}/hoodie/Mon11.png",
                "pointing finger smile": f"{SPRITE_DIR}/hoodie/Ika9.png",
                "sad": f"{SPRITE_DIR}/hoodie/Mon6.png",
                "crying": f"{SPRITE_DIR}/hoodie/Mon20.png",
                "sad smile": f"{SPRITE_DIR}/hoodie/Mon5.png",
                "neutral": f"{SPRITE_DIR}/hoodie/Mon3.png",
                "eyes close neutral": f"{SPRITE_DIR}/hoodie/Mon17.png",
                "neutral speaking": f"{SPRITE_DIR}/hoodie/Mon4.png",
                "eyes close neutral speaking": f"{SPRITE_DIR}/hoodie/Mon18.png",
                "horrified screams": f"{SPRITE_DIR}/hoodie/HorrifiedMonika8.png",
                "horrified speaking": f"{SPRITE_DIR}/hoodie/HorrifiedMonika5.png",
                "horrified babbling": f"{SPRITE_DIR}/hoodie/HorrifiedMonika6.png",
                "horrified surprised": f"{SPRITE_DIR}/hoodie/HorrifiedMonika4.png",
                "horrified no words": f"{SPRITE_DIR}/hoodie/HorrifiedMonika3.png",
                "horrified really surprised": f"{SPRITE_DIR}/hoodie/HorrifiedMonika2.png",
                "horrified": f"{SPRITE_DIR}/hoodie/HorrifiedMonika1.png",
                "horrified concerned": f"{SPRITE_DIR}/hoodie/HorrifiedMonika7.png",
                "serious": f"{SPRITE_DIR}/hoodie/Mon8.png",
                "ever serious": f"{SPRITE_DIR}/hoodie/Mon21.png",
                "disappointed": f"{SPRITE_DIR}/hoodie/Mon21.png",
                "serious pointing speaking": f"{SPRITE_DIR}/hoodie/Ika8.png",
                "serious pointing": f"{SPRITE_DIR}/hoodie/Ika7.png",
                "serious speaking": f"{SPRITE_DIR}/hoodie/Mon9.png",
                "serious pointing eyes close": f"{SPRITE_DIR}/hoodie/Ika15.png",
                "serious pointing speaking eyes close": f"{SPRITE_DIR}/hoodie/Ika16.png",
                "concerned": f"{SPRITE_DIR}/hoodie/Mon6.png",
                "concerned pointing": f"{SPRITE_DIR}/hoodie/Ika13.png",
                "concerned pointing speaking": f"{SPRITE_DIR}/hoodie/Ika14.png",
                "sad pointing smile looks away": f"{SPRITE_DIR}/hoodie/Ika12.png",
                "sad pointing smile": f"{SPRITE_DIR}//hoodie/Ika5.png",
                "sad pointing": f"{SPRITE_DIR}/hoodie/Ika6.png",
                "sad pointing smile speaking": f"{SPRITE_DIR}/hoodie/Ika11.png",
                "smile pointing speaking": f"{SPRITE_DIR}/hoodie/Ika10.png",
                "happy pointing speaking": f"{SPRITE_DIR}/hoodie/Ika2.png",
                "happy pointing": f"{SPRITE_DIR}/hoodie/Ika1.png",
                "neutral pointing speaking": f"{SPRITE_DIR}/hoodie/Ika4.png",
                "neutral pointing": f"{SPRITE_DIR}/hoodie/Ika3.png",
                "concerned speaking": f"{SPRITE_DIR}/hoodie/Mon7.png",
                "embarrass": f"{SPRITE_DIR}/hoodie/Mon19.png",
                "blushing with her eyes close": f"{SPRITE_DIR}/hoodie/Mon19.png",
                "nervous": f"{SPRITE_DIR}/hoodie/Mon13.png",
                "really nervous": f"{SPRITE_DIR}/hoodie/Mon15.png",
                "nervous speaking": f"{SPRITE_DIR}/hoodie/Mon16.png",
                "nervous laughing": f"{SPRITE_DIR}/hoodie/Mon14.png",
                "nervous laughing eyes close": f"{SPRITE_DIR}/hoodie/Mon12.png",
            },
            "pajamas": {
                "happy": f"{SPRITE_DIR}/pajamas/Mon1.png",
                "smile speaking": f"{SPRITE_DIR}/pajamas/Mon2.png",
                "lean smile": f"{SPRITE_DIR}/pajamas/3aa.png",
                "lean smile eyes close": f"{SPRITE_DIR}/pajamas/3ab.png",
                "lean happy eyes close speaking": f"{SPRITE_DIR}/pajamas/3ac.png",
                "lean happy speaking": f"{SPRITE_DIR}/pajamas/3ad.png",
                "lean happy wink": f"{SPRITE_DIR}/pajamas/3ae.png",
                "eyes close smile": f"{SPRITE_DIR}/pajamas/Mon10.png",
                "eyes close smile speaking": f"{SPRITE_DIR}/pajamas/Mon11.png",
                "pointing finger smile": f"{SPRITE_DIR}/pajamas/Ika9.png",
                "lean wink point smile": f"{SPRITE_DIR}/pajamas/3Ika.png",
                "sad": f"{SPRITE_DIR}/pajamas/Mon6.png",
                "crying": f"{SPRITE_DIR}/pajamas/Mon20.png",
                "sad smile": f"{SPRITE_DIR}/pajamas/Mon5.png",
                "neutral": f"{SPRITE_DIR}/pajamas/Mon3.png",
                "eyes close neutral": f"{SPRITE_DIR}/pajamas/Mon17.png",
                "neutral speaking": f"{SPRITE_DIR}/pajamas/Mon4.png",
                "eyes close neutral speaking": f"{SPRITE_DIR}/pajamas/Mon18.png",
                "pissed lean": f"{SPRITE_DIR}/pajamas/3bd.png",
                "mad speaking lean": f"{SPRITE_DIR}/pajamas/3ba.png",
                "mad leaning": f"{SPRITE_DIR}/pajamas/3bb.png",
                "mad pitting face lean": f"{SPRITE_DIR}/pajamas/3bc.png",
                "horrified screams": f"{SPRITE_DIR}/pajamas/HorrifiedMonika8.png",
                "horrified speaking": f"{SPRITE_DIR}/pajamas/HorrifiedMonika5.png",
                "horrified babbling": f"{SPRITE_DIR}/pajamas/HorrifiedMonika6.png",
                "horrified surprised": f"{SPRITE_DIR}/pajamas/HorrifiedMonika4.png",
                "horrified no words": f"{SPRITE_DIR}/pajamas/HorrifiedMonika3.png",
                "horrified really surprised": f"{SPRITE_DIR}/pajamas/HorrifiedMonika2.png",
                "horrified": f"{SPRITE_DIR}/pajamas/HorrifiedMonika1.png",
                "horrified concerned": f"{SPRITE_DIR}/pajamas/HorrifiedMonika7.png",
                "serious": f"{SPRITE_DIR}/pajamas/Mon8.png",
                "ever serious": f"{SPRITE_DIR}/pajamas/Mon21.png",
                "disappointed": f"{SPRITE_DIR}/pajamas/Mon21.png",
                "serious pointing speaking": f"{SPRITE_DIR}/pajamas/Ika8.png",
                "serious pointing": f"{SPRITE_DIR}/pajamas/Ika7.png",
                "serious speaking": f"{SPRITE_DIR}/pajamas/Mon9.png",
                "serious pointing eyes close": f"{SPRITE_DIR}/pajamas/Ika15.png",
                "serious pointing speaking eyes close": f"{SPRITE_DIR}/pajamas/Ika16.png",
                "concerned": f"{SPRITE_DIR}/pajamas/Mon6.png",
                "concerned pointing": f"{SPRITE_DIR}/pajamas/Ika13.png",
                "concerned pointing speaking": f"{SPRITE_DIR}/pajamas/Ika14.png",
                "sad pointing smile looks away": f"{SPRITE_DIR}/pajamas/Ika12.png",
                "sad pointing smile": f"{SPRITE_DIR}//pajamas/Ika5.png",
                "sad pointing": f"{SPRITE_DIR}/pajamas/Ika6.png",
                "sad pointing smile speaking": f"{SPRITE_DIR}/pajamas/Ika11.png",
                "smile pointing speaking": f"{SPRITE_DIR}/pajamas/Ika10.png",
                "happy pointing speaking": f"{SPRITE_DIR}/pajamas/Ika2.png",
                "happy pointing": f"{SPRITE_DIR}/pajamas/Ika1.png",
                "neutral pointing speaking": f"{SPRITE_DIR}/pajamas/Ika4.png",
                "neutral pointing": f"{SPRITE_DIR}/pajamas/Ika3.png",
                "concerned speaking": f"{SPRITE_DIR}/pajamas/Mon7.png",
                "embarrass": f"{SPRITE_DIR}/pajamas/Mon19.png",
                "blushing with her eyes close": f"{SPRITE_DIR}/pajamas/Mon19.png",
                "smirk lean": f"{SPRITE_DIR}/pajamas/3ca.png",
                "leaning kiss": f"{SPRITE_DIR}/pajamas/3cb.png",
                "blushing leaning": f"{SPRITE_DIR}/pajamas/3cc.png",
                "surprise speaking lean": f"{SPRITE_DIR}/pajamas/3da.png",
                "concerned speaking lean": f"{SPRITE_DIR}/pajamas/3ea.png",
                "my brother in christ": f"{SPRITE_DIR}/pajamas/3fa.png",
                "your joking. right?": f"{SPRITE_DIR}/pajamas/3fa.png",
                "nervous": f"{SPRITE_DIR}/pajamas/Mon13.png",
                "really nervous": f"{SPRITE_DIR}/pajamas/Mon15.png",
                "has a gun": f"{SPRITE_DIR}/pajamas/Gun.png",
                "oh shit she packing heat!": f"{SPRITE_DIR}/pajamas/Gun.png",
                "threatened": f"{SPRITE_DIR}/pajamas/with_gun.png",
                "nervous speaking": f"{SPRITE_DIR}/pajamas/Mon16.png",
                "nervous laughing": f"{SPRITE_DIR}/pajamas/Mon14.png",
                "nervous laughing eyes close": f"{SPRITE_DIR}/pajamas/Mon12.png",
            },
            "white summer dress": {
                "happy": f"{SPRITE_DIR}/dress/Mon1.png",
                "smile speaking": f"{SPRITE_DIR}/dress/Mon2.png",
                "eyes close smile": f"{SPRITE_DIR}/dress/Mon10.png",
                "eyes close smile speaking": f"{SPRITE_DIR}/dress/Mon11.png",
                "pointing finger smile": f"{SPRITE_DIR}/dress/Ika9.png",
                "sad": f"{SPRITE_DIR}/dress/Mon6.png",
                "crying": f"{SPRITE_DIR}/dress/Mon20.png",
                "sad smile": f"{SPRITE_DIR}/dress/Mon5.png",
                "neutral": f"{SPRITE_DIR}/dress/Mon3.png",
                "eyes close neutral": f"{SPRITE_DIR}/dress/Mon17.png",
                "neutral speaking": f"{SPRITE_DIR}/dress/Mon4.png",
                "eyes close neutral speaking": f"{SPRITE_DIR}/dress/Mon18.png",
                "horrified screams": f"{SPRITE_DIR}/dress/HorrifiedMonika8.png",
                "horrified speaking": f"{SPRITE_DIR}/dress/HorrifiedMonika5.png",
                "horrified babbling": f"{SPRITE_DIR}/dress/HorrifiedMonika6.png",
                "horrified surprised": f"{SPRITE_DIR}/dress/HorrifiedMonika4.png",
                "horrified no words": f"{SPRITE_DIR}/dress/HorrifiedMonika3.png",
                "horrified really surprised": f"{SPRITE_DIR}/dress/HorrifiedMonika2.png",
                "horrified": f"{SPRITE_DIR}/dress/HorrifiedMonika1.png",
                "horrified concerned": f"{SPRITE_DIR}/dress/HorrifiedMonika7.png",
                "serious": f"{SPRITE_DIR}/dress/Mon8.png",
                "ever serious": f"{SPRITE_DIR}/dress/Mon21.png",
                "disappointed": f"{SPRITE_DIR}/dress/Mon21.png",
                "serious pointing speaking": f"{SPRITE_DIR}/dress/Ika8.png",
                "serious pointing": f"{SPRITE_DIR}/dress/Ika7.png",
                "serious speaking": f"{SPRITE_DIR}/dress/Mon9.png",
                "serious pointing eyes close": f"{SPRITE_DIR}/dress/Ika15.png",
                "serious pointing speaking eyes close": f"{SPRITE_DIR}/dress/Ika16.png",
                "concerned": f"{SPRITE_DIR}/dress/Mon6.png",
                "concerned pointing": f"{SPRITE_DIR}/dress/Ika13.png",
                "concerned pointing speaking": f"{SPRITE_DIR}/dress/Ika14.png",
                "sad pointing smile looks away": f"{SPRITE_DIR}/dress/Ika12.png",
                "sad pointing smile": f"{SPRITE_DIR}//dress/Ika5.png",
                "sad pointing": f"{SPRITE_DIR}/dress/Ika6.png",
                "sad pointing smile speaking": f"{SPRITE_DIR}/dress/Ika11.png",
                "smile pointing speaking": f"{SPRITE_DIR}/dress/Ika10.png",
                "happy pointing speaking": f"{SPRITE_DIR}/dress/Ika2.png",
                "happy pointing": f"{SPRITE_DIR}/dress/Ika1.png",
                "neutral pointing speaking": f"{SPRITE_DIR}/dress/Ika4.png",
                "neutral pointing": f"{SPRITE_DIR}/dress/Ika3.png",
                "concerned speaking": f"{SPRITE_DIR}/dress/Mon7.png",
                "embarrass": f"{SPRITE_DIR}/dress/Mon19.png",
                "blushing with her eyes close": f"{SPRITE_DIR}/dress/Mon19.png",
                "nervous": f"{SPRITE_DIR}/dress/Mon13.png",
                "really nervous": f"{SPRITE_DIR}/dress/Mon15.png",
                "nervous speaking": f"{SPRITE_DIR}/dress/Mon16.png",
                "nervous laughing": f"{SPRITE_DIR}/dress/Mon14.png",
                "nervous laughing eyes close": f"{SPRITE_DIR}/dress/Mon12.png",
            }
        }

    def _pick_casual_variant(self):
        today = _today_date()
        if self._last_casual_date != today:
            variants = list(self.sprites_by_outfit["casual_variants"].keys())
            random.seed(today)  # so everyone picks the same for the day
            self._selected_casual_variant = random.choice(variants)
            self._last_casual_date = today
        return self._selected_casual_variant

    
    def _extract_all_emotions(self):
        all_emotions = set()
        for outfit in self.sprites_by_outfit.values():
            all_emotions.update(outfit.keys())
        return list(all_emotions)

    def get_sprite(self, emotion, outfit):
        if outfit == "casual":
            variant = self._pick_casual_variant()
            variant_map = self.sprites_by_outfit["casual_variants"].get(variant, {})
            return variant_map.get(emotion, variant_map.get("neutral"))

        outfit_sprites = self.sprites_by_outfit.get(outfit)
        if not outfit_sprites:
            return None

        path = outfit_sprites.get(emotion)
        if path:
            return path

        # fallback to neutral
        return outfit_sprites.get(emotion, outfit_sprites.get("neutral"))

    async def classify(self, text, openai_client):
        try:
            prompt = (
                "Return ONLY one label from this list: \n"
                + ", ".join(self.valid) +
                "\nDescribe this message's emotion using one of the labels only."
            )

            response = openai_client.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "system", "content": prompt},
                    {"role": "user", "content": text}
                ],
                temperature=0
            )

            emotion = response.choices[0].message.content.strip().lower()
            if emotion in self.valid:
                return emotion
            return "neutral"
        except Exception as e:
            print(f"[ {emotion} ] is not working. the error is: {e}")
