name: Auto Update JSON

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt || true
      - name: Run script to generate/update JSON (memory)
        run: python memory.py
      - name: Run script to generate/update JSON (user's)
        run: python user_tracker.py
      - name: Run script to generate/update JSON (server's)
        run: python servers_tracker.py
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add memory.json
          git add server.json
          git add users.json
          git commit -m "Auto-update output.json" || echo "No changes to commit"
          git push
